### ISSUE TITLE
Tiles are empty when page is loaded without trailing slash behind VHM

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.blocks#55]
I have a site behind Apache configured as follows:

```
ProxyPass http://foo.org:9081/VirtualHostBase/https/foo.org:443/plonesiteid/VirtualHostRoot/_vh_mysite
```

The home page is a `collective.cover.content` item type, and when accessing Zope directly at `:9081` everything is fine.  When going through Apache, I see that

* https://foo.org/mysite   all the tiles are empty
* https://foo.org/mysite/   works fine

I've debugged the `collective.cover` code all the way until the tiles are rendered, and in both cases the rendered HTML is exactly the same, with `<div data-tile="@@tilename/tileid">`.  So the next step is the transform performed by `plone.app.blocks`, IIUC.  When the URL is lacking a trailing slash the transform does nothing.

I'm using `plone.app.blocks 2.2.1` on Plone 4.3.9.  There are no errors in the logs.

**Comment by datakurre** [comment]
I recall seeing this, but because it was easy to add the trailing slash in Apache, I did not bother to look further. Yet, this probably is a real issue related to VirtualHost-paths.

I assume, this only happens at portal root?

**Comment by fulv** [comment]
Yes, only at portal root.

**Comment by fulv** [comment]
By the way, how did you add the trailing slash in Apache?
The simple minded way only works _kind of_:

    RewriteRule ^/home$ /home/

This is a 301 redirect, and it breaks all actions done in `folder_contents` on the site root because those actions use POST and the 301 turns them into GETs.

This might be fixed with a `[R=307,L]`, but the IT department of my client **hates** making these changes to the Apache configs, so I need to find a real fix.

**Comment by datakurre** [comment]
I agree this should be fixed, but first the real reason should be discovered. I believe all virtual host related path resolving happens actually in plone.subrequest. So, logging Plone subrequest should bring some light. I assume that for some reason tiles get rendered agains the root instead of the default page. Otherwise there should be errors logged.

**Comment by mauritsvanrees** [comment]
I still see this. Just tried it locally, with Plone 5.1 and collective.cover master. With a cover as default page on the site root, this works:

    http://localhost:8080/VirtualHostBase/http/localhost:9200/Plone/VirtualHostRoot/_vh_mysite/

But without a slash at the end it fails. I tried simply with that url in my browser. Nothing is running op port 9200 is this example.

This is not a problem for me. I was simply looking through issues because I ran into a [different issue](https://github.com/plone/Products.CMFPlone/issues/2995).
